org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

android.useAndroidX=true
android.nonTransitiveRClass=true

GROUP=io.github.maniramezan.compose
# x-release-please-start-version
VERSION_NAME=0.7.0
# x-release-please-end

POM_NAME=Compose UI System Design
POM_DESCRIPTION=Reusable Kotlin-first Jetpack Compose design system for Android apps.
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/maniramezan/ComposeUIComponents
POM_LICENSE_NAME=MIT License
POM_LICENSE_URL=https://opensource.org/licenses/MIT
POM_LICENSE_DIST=repo
POM_SCM_URL=https://github.com/maniramezan/ComposeUIComponents
POM_SCM_CONNECTION=scm:git:git://github.com/maniramezan/ComposeUIComponents.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/maniramezan/ComposeUIComponents.git
POM_DEVELOPER_ID=maniramezan
POM_DEVELOPER_NAME=Mani Ramezan
POM_DEVELOPER_URL=https://github.com/maniramezan

SONATYPE_HOST=CENTRAL_PORTAL
RELEASE_SIGNING_ENABLED=true
