config:
  validation: true

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
  NewLineAtEndOfFile:
    active: false
  UnusedPrivateClass:
    active: false
  UnusedPrivateFunction:
    active: false
  UnusedPrivateProperty:
    active: false

complexity:
  LongMethod:
    active: false
  LongParameterList:
    active: false
  TooManyFunctions:
    active: false
  CyclomaticComplexMethod:
    active: false

naming:
  MatchingDeclarationName:
    active: false
  FunctionNaming:
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
